---
- job:
    name: rdo-website-deploy
    parent: base
    description: Install and build website
    run: playbooks/deploy.yaml
    nodeset:
      nodes:
        - name: rdo-centos-8
          label: rdo-centos-8
- project:
    name: rdo-website
    check:
      jobs:
        - rdo-website-deploy
    gate:
      jobs:
        - rdo-website-deploy

