---
- job:
    name: rdo-website-build
    parent: base
    description: Build RDO website
    run: playbooks/build.yaml
    post-run: playbooks/retrieve-logs.yaml
    nodeset: rdo-centos-7

- project:
    name: rdo-website
    check:
      jobs:
        - rdo-website-build
    gate:
      jobs:
        - rdo-website-build

