---
- job:
    name: rdo-website-build
    parent: base
    description: Build RDO website
    run: playbooks/build.yaml
    nodeset:
      nodes:
        - name: cloud-centos-7
          label: cloud-centos-7
- project:
    name: rdo-website
    check:
      jobs:
        - rdo-website-build
    gate:
      jobs:
        - rdo-website-build

