- hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name:
          - rubygem-bundler
          - ruby-devel
          - rubygems-devel
          - gcc
          - gcc-c++
          - make
          - redhat-rpm-config
          - zlib-devel
          - ImageMagick
        state: present

    - name: Build RDO website
      shell:
        cmd: |
          export PATH=$PATH:$HOME/bin
          bundle install
          bundle exec middleman build --verbose
        chdir: '{{ zuul.project.src_dir }}'

